### ISSUE TITLE
Mismatch of source catalog version in the code and in the specifications

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/radar-commons-android#194]
The source catalog version in most plugins is taken from `BuildConfig.VERSION_NAME` which currently is 1.0.0-alpha2. But in the specifications, this is not the case. For example, empatica e4 version is 1.1.0 in the latest specs. Hence the source is not available on the Management portal and cannot be registered. The code should use fixed versions based on the latest specs.

**Comment by blootsvoets** [comment]
This assessment is correct. The issue is limited because of the fact that the version number of the specifications is not considered for actual matching. E.g. the specification versions are not used in the pRMT app, only the vendor/model combination. Also the specification itself is not used, Firebase config is used instead.

**Comment by blootsvoets** [comment]
For activating functionality, the app only checks whether the vendor and model is present. For registering a source, it takes the highest version it finds:

```
.maxBy { if (it.catalogVersion.startsWith('v')) it.catalogVersion.substring(1) else it.catalogVersion }
```

**Comment by yatharthranjan** [comment]
Ok, thanks. That's good to know
